local objects = {
    {
      id = 2,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 207.84,
      y = 241.227,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 3,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 312.163,
      y = 214.247,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 4,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 343.34,
      y = 214.847,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 5,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 407.326,
      y = 124.967,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 9,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 631.127,
      y = 232.834,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 10,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 664.103,
      y = 233.433,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 11,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 583.762,
      y = 120.117,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 12,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 360.128,
      y = 88.9401,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 13,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 233.022,
      y = 72.7521,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 14,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 75.3383,
      y = 57.1636,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 16,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 54.9534,
      y = 57.1636,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 17,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 23.9277,
      y = 39.9277,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    },
    {
      id = 19,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 503.754,
      y = 242.158,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    },
    {
      id = 20,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 767.904,
      y = 167.036,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    },
    {
      id = 21,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 504.935,
      y = 166.695,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    }
  }

return objects